### PR TITLE
removed old interface, replaced ienumerables with ilists

### PR DESCRIPTION
**Pull request by herrozerro**
Replaced IEnumerables with ILists for adding and removing items.  Removed old interface that isn't used anymore.  Updated to 1.0.4

### CODE REVIEW

**Comment by herrozerro** [comment]
Please approve.  If merging, please rebase and merge

**Review by williamkeller — APPROVED** [review]
Looks good, from my extremely limited vantage point. When I last used C#, templates hadn't been introduced yet.  :smile:

What is the difference in usage between IEnumerable and IList?

+1 for using versioning

**Comment by herrozerro** [comment]
IEnumerable is just a generic readonly collection interface.  IList allows for indexing and Add/Remove.

**Review by williamkeller — APPROVED** [review]
Trying approve again

**Comment by williamkeller** [comment]
I don't want to merge without being able to run it. That just seems wrong.

**Pull request merged**
